import { Product } from '@/types'

export const WHATSAPP_NUMBER = '5511999999999' // Trocar pelo número real do petshop

export const CATEGORY_LABELS: Record<string, string> = {
  cachorros: 'Cachorros',
  gatos: 'Gatos',
  passaros: 'Pássaros',
  peixes: 'Peixes',
  outros: 'Outros',
}

export const CATEGORY_COLORS: Record<string, { bg: string; text: string; border: string; dot: string }> = {
  cachorros: { bg: 'bg-white', text: 'text-[#0F766E]', border: 'border-gray-100', dot: 'bg-[#0F766E]' },
  gatos:     { bg: 'bg-white', text: 'text-[#0F766E]', border: 'border-gray-100', dot: 'bg-[#0F766E]' },
  passaros:  { bg: 'bg-white', text: 'text-[#0F766E]', border: 'border-gray-100', dot: 'bg-[#0F766E]' },
  peixes:    { bg: 'bg-white', text: 'text-[#0F766E]', border: 'border-gray-100', dot: 'bg-[#0F766E]' },
  outros:    { bg: 'bg-white', text: 'text-[#0F766E]', border: 'border-gray-100', dot: 'bg-[#0F766E]' },
}

export const CATEGORY_DESC: Record<string, string> = {
  cachorros: 'Ração, acessórios e higiene',
  gatos:     'Areia, ração e arranhadores',
  passaros:  'Sementes, gaiolas e poleiros',
  peixes:    'Aquários, rações e decoração',
  outros:    'Hamsters, coelhos e mais',
}

export const DEFAULT_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Ração Golden Adulto Frango 15kg',
    description: 'Ração premium para cães adultos de todas as raças, com frango e arroz. Fórmula balanceada com vitaminas e minerais.',
    price: 189.90,
    originalPrice: 219.90,
    category: 'cachorros',
    image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=400&h=400&fit=crop',
    inStock: true,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Coleira Antipulgas Seresto Cão',
    description: 'Coleira antipulgas e carrapatos com proteção de até 8 meses. Para cães acima de 8kg.',
    price: 149.90,
    category: 'cachorros',
    image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=400&fit=crop',
    inStock: true,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Brinquedo Corda Colorida para Cão',
    description: 'Brinquedo de corda multicolorido para cães de médio e grande porte. Ideal para brincadeiras de cabo de guerra.',
    price: 24.90,
    category: 'cachorros',
    image: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=400&h=400&fit=crop',
    inStock: true,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Ração Whiskas Gato Adulto Atum 3kg',
    description: 'Ração completa para gatos adultos com sabor atum. Rica em proteínas e com taurina para saúde cardíaca.',
    price: 64.90,
    originalPrice: 79.90,
    category: 'gatos',
    image: 'https://images.unsplash.com/photo-1548767797-d8c844163c4a?w=400&h=400&fit=crop',
    inStock: true,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Arranhador Gato Torre com Brinquedo',
    description: 'Torre arranhadora com brinquedos suspensos, cama no topo e sisal natural. Perfeito para exercitar seu gato.',
    price: 129.90,
    category: 'gatos',
    image: 'https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=400&h=400&fit=crop',
    inStock: true,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Caixa de Areia Fechada para Gatos',
    description: 'Caixa higiênica fechada com porta e filtro de carvão ativado. Elimina odores e mantém o ambiente limpo.',
    price: 89.90,
    category: 'gatos',
    image: 'https://images.unsplash.com/photo-1518791841217-8f162f1912da?w=400&h=400&fit=crop',
    inStock: false,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Mistura para Pássaros Tropical 500g',
    description: 'Mistura de sementes premium para pássaros tropicais. Contém alpiste, painço, girassol e outros grãos selecionados.',
    price: 18.90,
    category: 'passaros',
    image: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=400&h=400&fit=crop',
    inStock: true,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Gaiola Decorativa para Calopsita',
    description: 'Gaiola espaçosa com poleiros, comedouros e bebedouros inclusos. Design elegante para decorar sua casa.',
    price: 199.90,
    originalPrice: 249.90,
    category: 'passaros',
    image: 'https://images.unsplash.com/photo-1434943046065-eb24cb3bba80?w=400&h=400&fit=crop',
    inStock: true,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'Ração para Peixes Tetra Min 100g',
    description: 'Alimento completo para peixes tropicais. Flocos de alta digestibilidade que não turvam a água.',
    price: 29.90,
    category: 'peixes',
    image: 'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=400&h=400&fit=crop',
    inStock: true,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '10',
    name: 'Aquário Kit Completo 30L',
    description: 'Kit completo com aquário de 30 litros, filtro, iluminação LED, termômetro e manual de instruções.',
    price: 329.90,
    category: 'peixes',
    image: 'https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=400&h=400&fit=crop',
    inStock: true,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '11',
    name: 'Ração para Hamster Vitapol 500g',
    description: 'Mistura completa de sementes e pellets para hamsters. Fórmula enriquecida com vitaminas A, D3 e E.',
    price: 22.90,
    category: 'outros',
    image: 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=400&h=400&fit=crop',
    inStock: true,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '12',
    name: 'Shampoo Pet Neutro 500ml',
    description: 'Shampoo neutro para cães e gatos. Fórmula suave com pH balanceado, sem parabenos. Deixa o pelo macio e brilhante.',
    price: 34.90,
    originalPrice: 44.90,
    category: 'cachorros',
    image: 'https://images.unsplash.com/photo-1584305574647-0cc949a2bb9f?w=400&h=400&fit=crop',
    inStock: true,
    featured: false,
    createdAt: new Date().toISOString(),
  },
]
